testing failure

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -44,6 +44,11 @@ jobs:
       version: ${{ steps.version.outputs.version }}
     steps:
     # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
+    - name: Simulate failure
+      run: |
+        echo "Simulating a failure..."
+        exit 1
+
     - name: Checkout code 
       uses: actions/checkout@v2
     - name: Set up Python 3.10
